### PR TITLE
parallel implementation

### LINKED ISSUE #6: To do
- [x]  Improve description of functions in ?
- [x] Add heat map visualisation
- [x] Add web page for visualisations
- [ ] Add feature selection method as in #11 
- [x] Add function to deal with SingleCellExperiment objects
- [x] Optimize memory usage in generating pathway matrices at in #17 
- [x] Allow assay specification in `seurat_extract()` and `compare_seurat()` as in #28 
- [ ] Parallel implementation of compare_pathways()

### PR DESCRIPTION
**Pull request by jiwen90**
This resolves #6 and #17.

### CODE REVIEW

**Comment by jackbibby1** [comment]
Hi. Thanks for this -- have been meaning to implement some parallelisation of the pathways, but haven't had the time yet. I'm currently getting an error when I run this on my machine, using the naive_cd4.rds dataset from [this tutorial](https://jackbibby1.github.io/SCPA/articles/comparing_two_populations.html).

```
df <- readRDS("naive_cd4.rds")

pathways <- msigdbr("Homo sapiens", "H") %>%
  format_pathways()

p1 <- seurat_extract(df, meta1 = "Hour", value_meta1 = "0")
p2 <- seurat_extract(df, meta1 = "Hour", value_meta1 = "24")

scpa_out <- compare_pathways_parallel(samples = list(p1, p2), pathways = pathways, cores = 2)

--------

Cell numbers in population 1 = 4428
Cell numbers in population 2 = 5919
- If greater than 500 cells, these populations will be downsampled

All 50 pathways passed the min/max genes threshold

Calculating pathway fold changes...

Performing a two-sample analysis with SCPA...
Error in { : task 1 failed - "multi-argument returns are not permitted"

```

Is this running fine on your end?

Jack

**Comment by jiwen90** [comment]
Hi,

It works for me. The "multi-argument returns are not permitted" is likely due to the tryCatch error message, which I just removed. I'm not sure what error was thrown on your end -- can you run it again, optionally without the tryCatch, to see what's the problem?

```
> df <- readRDS("naive_cd4.rds")

> pathways <- msigdbr("Homo sapiens", "H") %>%
  format_pathways()

> p1 <- seurat_extract(df, meta1 = "Hour", value_meta1 = "0")
> p2 <- seurat_extract(df, meta1 = "Hour", value_meta1 = "24")

> scpa_out <- compare_pathways_parallel(samples = list(p1, p2), pathways = pathways, cores = 2)

Cell numbers in population 1 = 4428
Cell numbers in population 2 = 5919
- If greater than 500 cells, these populations will be downsampled

All 50 pathways passed the min/max genes threshold

Calculating pathway fold changes...

Performing a two-sample analysis with SCPA...
Loading required package: doParallel
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel

> scpa_out
                                      Pathway          Pval       adjPval
1          HALLMARK_INTERFERON_GAMMA_RESPONSE 5.341958e-106 2.670979e-104
2                HALLMARK_ALLOGRAFT_REJECTION 1.253504e-102 6.267519e-101
3          HALLMARK_INTERFERON_ALPHA_RESPONSE  2.589021e-99  1.294511e-97
4              HALLMARK_INFLAMMATORY_RESPONSE  1.061001e-89  5.305003e-88
5            HALLMARK_TNFA_SIGNALING_VIA_NFKB  3.796084e-88  1.898042e-86
6            HALLMARK_IL6_JAK_STAT3_SIGNALING  4.522036e-82  2.261018e-80
7                     HALLMARK_MYC_TARGETS_V1  4.522036e-82  2.261018e-80
8                     HALLMARK_UV_RESPONSE_UP  1.379483e-80  6.897414e-79
9                          HALLMARK_APOPTOSIS  4.076176e-79  2.038088e-77
10                        HALLMARK_COMPLEMENT  3.234390e-76  1.617195e-74
...
```

**Comment by jackbibby1** [comment]
Hmm, odd. New error, but this time:

```
df <- readRDS("naive_cd4.rds")

pathways <- msigdbr("Homo sapiens", "H") %>%
  format_pathways()

p1 <- seurat_extract(df, meta1 = "Hour", value_meta1 = "0")
p2 <- seurat_extract(df, meta1 = "Hour", value_meta1 = "24")

scpa_out <- compare_pathways_parallel(samples = list(p1, p2), pathways = pathways, cores = 2)

-------

Cell numbers in population 1 = 4428
Cell numbers in population 2 = 5919
- If greater than 500 cells, these populations will be downsampled

All 50 pathways passed the min/max genes threshold

Calculating pathway fold changes...

Performing a two-sample analysis with SCPA...
Error in `dplyr::arrange()`:
! Problem with the implicit `transmute()` step.
✖ Problem while computing `..1 = qval`.
Caused by error in `mask$eval_all_mutate()`:
! object 'qval' not found
Run `rlang::last_error()` to see where the error occurred.
```

Having a closer look, in the `scpa_result <- foreach(pathway = pathways_filtered) %dopar% { ... },
        error = function(e) {
        })
    }` part of the function I'm just getting a bunch of NULL values, which will be causing the error with `arrange`...

```
> scpa_result

[[1]]
NULL

[[2]]
NULL

...

[[49]]
NULL

[[50]]
NULL
```

**Comment by jiwen90** [comment]
Can you 

1. Check that all required packages are installed (doParallel and others)
2. Run without tryCatch? The NULL values are from the catch block, which indicates an error inside the main function.

Thanks!

**Comment by jackbibby1** [comment]
2. Yup, my bad -- that was me being an idiot. I ran without the tryCatch and it's running fine now

**Comment by jiwen90** [comment]
The tryCatch block itself shouldn't cause errors and should be included for safe cluster shutdown. If you can run it with the tryCatch block, then this should be good to merge. Otherwise we need to find the underlying problem.

**Comment by jackbibby1** [comment]
Yup -- looks like I caused an issue with the %>% dependency when I was running it. Anyway, it all looks to be working well now, so have merged everything. Thanks a bunch for that, it was really useful

**Comment by jiwen90** [comment]
It may be worth noting that the greatest speedup comes from running many pathways (eg 1000+). With only 50 pathways, as in the tutorial, the processes spawn time begins to exceed actual execution time.

**Comment by jackbibby1** [comment]
Yeah, good point -- I'll add some more benchmarking with increasing gene set sizes

**Comment by jiwen90** [comment]
Small usability point - I would remove the parallel parameter and instead set cores=1 as default. If cores > 1, then use parallel processing. This avoids an extra parameter and user confusion.

**Comment by jackbibby1** [comment]
Hmm yeah, I think that's probably best on reflection. I'll change it up in the next version

**Pull request merged**
